"""
Django settings for SCIENTIFICJOURNAL project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9pcv_4+m$#(=3#+57h^ze&a$+rw@qsyydnggy5^5-la6bppp7g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'debug_toolbar',
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    'crispy_forms',
    'dashboards',
    'manuscript',
    'journals',
]

MIDDLEWARE = [
    
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


INTERNAL_IPS = ("127.0.0.1", "172.17.0.1")

ROOT_URLCONF = 'SCIENTIFICJOURNAL.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ './Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'SCIENTIFICJOURNAL.wsgi.application'

AUTH_USER_MODEL = 'accounts.Account'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'scientificjournal',
    'USER': 'root',
    'PASSWORD': '',
    'HOST': '',
    'PORT': '3308',
    'OPTIONS': {
    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
}
}
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us' #'fr' 

TIME_ZONE = 'GMT'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = (
    ('en',_('English')),
    ('fr',_('French'))
)

LOCALE_PATHS = [
   './locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# The actual folder where static files will be collected
STATIC_ROOT = 'Static'
STATICFILES_DIRS = [
    BASE_DIR / "Templates",
    './Templates/Login',
    './Templates/Home',
    './dashboards/Templates/dashboards',
    
]
# Location of folders that will be added to static folder
#STATICFILES_DIRS = (
#   os.path.join(BASE_DIR, "Login", "Register", "static"),
#)
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

MEDIA_ROOT = os.path.join (BASE_DIR , 'media')
MEDIA_URL = '/media/'






EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
DEFAULT_FROM_EMAIL = 'admin@scientificjournal.com'
EMAIL_FILE_PATH = 'sent_emails'



# Logging Information
# LOGGING = {
#     'version': 1,
#     # Version of logging
#     'disable_existing_loggers': False,
 
#     'formatters':{
#         'Simple_Format':{
#             'format': '{levelname} {message}',
#             'style': '{',
#         }
#     },
 
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': './logs/log_file1.log',
#         },
 
#         'console': {
#             'level':'INFO',
#             'class': 'logging.StreamHandler',
#         },
#     },
 
#     'loggers': {
#         'django': {
#             'handlers': ['file', 'console'],
#             'level':  os.getenv('DJANGO_LOG_LEVEL', 'DEBUG'),
#         },
#     },
# }