# Generated by Django 3.2.8 on 2021-11-10 15:42

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=55, verbose_name='first name')),
                ('last_name', models.CharField(max_length=55, verbose_name='last name')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True, verbose_name='Account active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is administrator')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='super user')),
                ('is_reviewer', models.BooleanField(default=False, verbose_name='reviewer')),
                ('is_editor', models.BooleanField(default=False, verbose_name='editor')),
                ('is_chief_editor', models.BooleanField(default=False, verbose_name='editor in chief')),
                ('is_author', models.BooleanField(default=False, verbose_name='author')),
                ('is_publisher', models.BooleanField(default=False, verbose_name='publisher')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.account')),
                ('profession', models.CharField(default=None, max_length=255, verbose_name='Profession')),
                ('institution', models.CharField(default=None, max_length=255, verbose_name='Institution')),
                ('domain_of_interest', models.CharField(default=None, max_length=255, verbose_name='Domain of Interest')),
                ('laboratory_affiliation', models.CharField(default=None, max_length=255, verbose_name='Laboratory Affiliation')),
                ('biography', models.TextField(default=None, max_length=700, verbose_name='Short biography')),
                ('resume', models.FileField(null=True, upload_to=accounts.models.author_directory_path, verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.account')),
                ('profession', models.CharField(default=None, max_length=255, verbose_name='Profession')),
                ('domain_of_research', models.CharField(default=None, max_length=255, verbose_name='Domain of Research')),
                ('biography', models.TextField(default=None, max_length=700, verbose_name='Short biography')),
                ('resume', models.FileField(null=True, upload_to=accounts.models.editor_directory_path, verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Editor',
                'verbose_name_plural': 'Editors',
            },
        ),
        migrations.CreateModel(
            name='EditorInChief',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.account')),
                ('profession', models.CharField(default=None, max_length=255, verbose_name='Profession')),
                ('domain_of_research', models.CharField(default=None, max_length=255, verbose_name='Domain of Research')),
                ('biography', models.TextField(default=None, max_length=700, verbose_name='Short biography')),
                ('resume', models.FileField(null=True, upload_to=accounts.models.editor_in_chief_directory_path, verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Editor In Chief',
                'verbose_name_plural': 'Editors In Chief',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.account')),
                ('affiliation', models.CharField(default=None, max_length=255, verbose_name='Affiliation')),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.account')),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('domain_of_research', models.CharField(default=None, max_length=255, verbose_name='Domain of Research')),
                ('biography', models.TextField(default=None, max_length=700, verbose_name='Short biography')),
                ('resume', models.FileField(null=True, upload_to=accounts.models.reviewer_directory_path, verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Reviewer',
                'verbose_name_plural': 'Reviewers',
            },
        ),
    ]
