# Generated by Django 3.2.8 on 2021-11-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Issue ID')),
            ],
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('journal_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Journal ID')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('volume_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Volume ID')),
            ],
        ),
    ]
